#!/usr/bin/env python3
"""
Load LeNet5 (maxpool) state_dict from a .pth file, then emit C headers:

  - lenet5_weights_fp32.h   — float32 weights/biases (no scale; values are native floats)
  - lenet5_weights_int8.h   — symmetric per-tensor quantized int8 + float scale each tensor
  - lenet5_weights_int16.h  — same for int16
  - lenet5_weights_int32.h  — same for int32

Memory order matches PyTorch contiguous tensors (C_CNN Tensor NCHW / GEMM layout).

Usage:
  python export_lenet5_weights_to_h.py --pth ../../ModelWeight/lenet5_mnist.pth --out-dir ./exported_headers
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import torch

# Order matches lenet5_model_maxpool + typical C wiring (conv1->C1, conv2->C3, conv3->C5, fc1->F6, fc2->F7)
STATE_DICT_KEYS = [
    "conv1.weight",
    "conv1.bias",
    "conv2.weight",
    "conv2.bias",
    "conv3.weight",
    "conv3.bias",
    "fc1.weight",
    "fc1.bias",
    "fc2.weight",
    "fc2.bias",
]

# C-safe identifier suffix (no dots)
C_NAMES = [
    "conv1_weight",
    "conv1_bias",
    "conv2_weight",
    "conv2_bias",
    "conv3_weight",
    "conv3_bias",
    "fc1_weight",
    "fc1_bias",
    "fc2_weight",
    "fc2_bias",
]

QUANT_KINDS = {
    "int8": (8, "int8_t", "INT8"),
    "int16": (16, "int16_t", "INT16"),
    "int32": (32, "int32_t", "INT32"),
}


def _load_state_dict(pth_path: Path) -> dict:
    try:
        obj = torch.load(pth_path, map_location="cpu", weights_only=True)
    except TypeError:
        obj = torch.load(pth_path, map_location="cpu")
    if isinstance(obj, dict) and "state_dict" in obj:
        obj = obj["state_dict"]
    if not isinstance(obj, dict):
        raise ValueError(f"Expected state_dict-like dict from {pth_path}")
    return obj


def _tensor_to_numpy(t: torch.Tensor) -> np.ndarray:
    if not t.is_contiguous():
        t = t.contiguous()
    return t.detach().cpu().numpy().astype(np.float32)


def symmetric_quantize(arr_f32: np.ndarray, bits: int) -> tuple[np.ndarray, float]:
    """Per-tensor symmetric quantization. Returns (quantized int array, scale)."""
    qmax = float((1 << (bits - 1)) - 1)
    qmin = float(-(1 << (bits - 1)))
    flat = arr_f32.reshape(-1)
    amax = float(np.max(np.abs(flat))) if flat.size else 0.0
    if amax <= 0.0:
        scale = 1.0
        q = np.zeros_like(arr_f32, dtype=np.float32)
    else:
        scale = amax / qmax
        q = np.round(arr_f32 / scale)
    q = np.clip(q, qmin, qmax)

    if bits == 8:
        dtype = np.int8
    elif bits == 16:
        dtype = np.int16
    elif bits == 32:
        dtype = np.int32
    else:
        raise ValueError(bits)
    return q.astype(dtype), scale


def _format_initializer_int(values: np.ndarray, per_line: int = 12) -> str:
    flat = values.flatten()
    lines: list[str] = []
    for i in range(0, flat.size, per_line):
        chunk = flat[i : i + per_line]
        lines.append("    " + ", ".join(str(int(v)) for v in chunk) + ",")
    return "\n".join(lines) if lines else "    /* empty */"


def _format_initializer_float(values: np.ndarray, per_line: int = 8) -> str:
    flat = values.astype(np.float32, copy=False).flatten()
    lines: list[str] = []
    for i in range(0, flat.size, per_line):
        chunk = flat[i : i + per_line]
        parts = [f"{float(v):.9e}f" for v in chunk]
        lines.append("    " + ", ".join(parts) + ",")
    return "\n".join(lines) if lines else "    /* empty */"


def _c_float_literal(scale: float) -> str:
    """Emit a single-precision C constant from a Python float."""
    s = np.float32(scale)
    return f"{float(s):.9e}f"


def emit_header(
    out_path: Path,
    tag: str,
    guard: str,
    entries: list[tuple[str, np.ndarray, str, float | None]],
) -> None:
    """
    entries: (c_symbol, array, c_element_type, scale_or_none)
      - If scale_or_none is float: emit `static const float <name>_scale = ...` then int array.
      - If None: emit only array (used for fp32).
    """
    lines: list[str] = [
        f"/* Auto-generated by export_lenet5_weights_to_h.py ({tag}) */",
        "/* Do not edit by hand. */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
        "/*",
        " * C_CNN name mapping:",
        " *   conv1 -> w_c1 / b_c1",
        " *   conv2 -> w_c3 / b_c3",
        " *   conv3 -> w_c5 / b_c5",
        " *   fc1   -> w_f6 / b_f6",
        " *   fc2   -> w_f7 / b_f7",
        " */",
        "",
    ]

    if tag != "fp32":
        lines.extend(
            [
                "/*",
                " * Integer tensors: per-tensor symmetric quant, dequant approx q * scale (float).",
                " */",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "/*",
                " * Float tensors: raw fp32 weights/biases; no separate scale constants.",
                " */",
                "",
            ]
        )

    for name, arr, ctype, scale in entries:
        n_elem = int(arr.size)
        if scale is not None:
            scale_name = f"{name}_scale"
            lines.append(f"static const float {scale_name} = {_c_float_literal(scale)};")
        lines.append(f"static const {ctype} {name}[{n_elem}] = {{")
        if ctype == "float":
            lines.append(_format_initializer_float(arr))
        else:
            lines.append(_format_initializer_int(arr))
        lines.append("};")
        lines.append("")

    lines.append(f"#endif /* {guard} */")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    default_pth = repo_root / "ModelWeight" / "lenet5_mnist.pth"
    default_out = Path(__file__).resolve().parent / "exported_headers"

    ap = argparse.ArgumentParser(description="Export LeNet5 .pth weights to C headers (fp32 + int8/16/32).")
    ap.add_argument("--pth", type=Path, default=default_pth, help="Path to .pth state_dict")
    ap.add_argument("--out-dir", type=Path, default=default_out, help="Output directory for .h files")
    args = ap.parse_args()

    pth_path: Path = args.pth
    out_dir: Path = args.out_dir

    if not pth_path.is_file():
        raise FileNotFoundError(f"Missing checkpoint: {pth_path}")

    sd = _load_state_dict(pth_path)
    missing = [k for k in STATE_DICT_KEYS if k not in sd]
    if missing:
        raise KeyError(f"state_dict missing keys: {missing}. Present: {list(sd.keys())}")

    # fp32: no scale lines; float arrays
    fp32_entries: list[tuple[str, np.ndarray, str, float | None]] = []
    for key, cname in zip(STATE_DICT_KEYS, C_NAMES):
        w = _tensor_to_numpy(sd[key])
        fp32_entries.append((cname, w, "float", None))
    emit_header(
        out_dir / "lenet5_weights_fp32.h",
        "fp32",
        "LENET5_WEIGHTS_FP32_H",
        fp32_entries,
    )
    print(f"Wrote {out_dir / 'lenet5_weights_fp32.h'}")

    for kind, (bits, ctype, macro) in QUANT_KINDS.items():
        entries: list[tuple[str, np.ndarray, str, float | None]] = []
        for key, cname in zip(STATE_DICT_KEYS, C_NAMES):
            w = _tensor_to_numpy(sd[key])
            q, scale = symmetric_quantize(w, bits)
            entries.append((cname, q, ctype, scale))

        emit_header(
            out_dir / f"lenet5_weights_{kind}.h",
            kind,
            f"LENET5_WEIGHTS_{macro}_H",
            entries,
        )
        print(f"Wrote {out_dir / f'lenet5_weights_{kind}.h'}")

    print("Done.")


if __name__ == "__main__":
    main()
