#!/usr/bin/env python3
"""
Convert images in this folder (testimg/) to LeNet5/MNIST-style input tensors and emit C headers:

  - ../exported_input_headers/testimg_inputs_fp32.h
  - ../exported_input_headers/testimg_inputs_int8.h
  - ../exported_input_headers/testimg_inputs_int16.h
  - ../exported_input_headers/testimg_inputs_int32.h

Pipeline (aligned with train_lenet5.py when MNIST normalize is on):
  grayscale -> resize 28x28 -> optional zero-pad to 32x32
  -> /255 -> (x - 0.1307) / 0.3081
  -> row-major flatten [H*W] for N=C=1 (matches C Tensor layout).

Requires: Pillow, numpy (no PyTorch).

Usage (run from anywhere):
  python export_testimg_inputs_to_h.py
  python export_testimg_inputs_to_h.py --pad-to-32
  python export_testimg_inputs_to_h.py --img-dir . --out-dir ../exported_input_headers
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import numpy as np
from PIL import Image, ImageOps

MNIST_MEAN = 0.1307
MNIST_STD = 0.3081

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".webp", ".gif", ".tif", ".tiff"}

QUANT_KINDS = {
    "int8": ("int8_t", "INT8"),
    "int16": ("int16_t", "INT16"),
    "int32": ("int32_t", "INT32"),
}


def _c_symbol_from_stem(stem: str) -> str:
    s = re.sub(r"[^0-9a-zA-Z_]", "_", stem)
    if not s:
        return "image"
    if s[0].isdigit():
        s = "img_" + s
    return s


def symmetric_quantize(arr_f32: np.ndarray, bits: int) -> tuple[np.ndarray, float]:
    qmax = float((1 << (bits - 1)) - 1)
    qmin = float(-(1 << (bits - 1)))
    flat = arr_f32.reshape(-1)
    amax = float(np.max(np.abs(flat))) if flat.size else 0.0
    if amax <= 0.0:
        scale = 1.0
        q = np.zeros_like(arr_f32, dtype=np.float32)
    else:
        scale = amax / qmax
        q = np.round(arr_f32 / scale)
    q = np.clip(q, qmin, qmax)
    if bits == 8:
        dtype = np.int8
    elif bits == 16:
        dtype = np.int16
    elif bits == 32:
        dtype = np.int32
    else:
        raise ValueError(bits)
    return q.astype(dtype), scale


def _format_initializer_int(values: np.ndarray, per_line: int = 12) -> str:
    flat = values.flatten()
    lines: list[str] = []
    for i in range(0, flat.size, per_line):
        chunk = flat[i : i + per_line]
        lines.append("    " + ", ".join(str(int(v)) for v in chunk) + ",")
    return "\n".join(lines) if lines else "    /* empty */"


def _format_initializer_float(values: np.ndarray, per_line: int = 8) -> str:
    flat = values.astype(np.float32, copy=False).flatten()
    lines: list[str] = []
    for i in range(0, flat.size, per_line):
        chunk = flat[i : i + per_line]
        parts = [f"{float(v):.9e}f" for v in chunk]
        lines.append("    " + ", ".join(parts) + ",")
    return "\n".join(lines) if lines else "    /* empty */"


def _c_float_literal(scale: float) -> str:
    s = np.float32(scale)
    return f"{float(s):.9e}f"


def load_and_preprocess(
    path: Path,
    *,
    pad_to_32: bool,
    mnist_normalize: bool,
) -> np.ndarray:
    img = Image.open(path)
    img = ImageOps.exif_transpose(img)
    img = img.convert("L")
    img = img.resize((28, 28), Image.Resampling.BILINEAR)
    if pad_to_32:
        img = ImageOps.expand(img, border=2, fill=0)

    arr = np.asarray(img, dtype=np.float32) / 255.0
    if mnist_normalize:
        arr = (arr - MNIST_MEAN) / MNIST_STD
    return arr


def emit_input_header(
    out_path: Path,
    tag: str,
    guard: str,
    entries: list[tuple[str, np.ndarray, str, float | None]],
    *,
    h: int,
    w: int,
) -> None:
    lines: list[str] = [
        f"/* Auto-generated by testimg/export_testimg_inputs_to_h.py ({tag}) */",
        "/* Do not edit by hand. */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
        f"/* 1 channel, {h}x{w}, row-major (h*W+w). */",
        "",
    ]

    for name, arr, ctype, scale in entries:
        n_elem = int(arr.size)
        if scale is not None:
            lines.append(f"static const float {name}_scale = {_c_float_literal(scale)};")
        lines.append(f"static const {ctype} {name}[{n_elem}] = {{")
        if ctype == "float":
            lines.append(_format_initializer_float(arr))
        else:
            lines.append(_format_initializer_int(arr))
        lines.append("};")
        lines.append("")

    lines.append(f"#endif /* {guard} */")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    default_img_dir = script_dir
    default_out = script_dir.parent / "exported_input_headers"

    ap = argparse.ArgumentParser(description="Export test images to LeNet-style C input headers.")
    ap.add_argument(
        "--img-dir",
        type=Path,
        default=default_img_dir,
        help="Folder containing images (default: this script's directory, i.e. testimg/)",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=default_out,
        help="Output directory for .h files (default: lenet5/exported_input_headers)",
    )
    ap.add_argument(
        "--pad-to-32",
        action="store_true",
        help="Pad to 32x32 for C lenet5 input (same order as torchvision Pad+ToTensor+Normalize).",
    )
    ap.add_argument(
        "--no-mnist-normalize",
        action="store_true",
        help="Keep [0,1] only after /255; skip (x-mean)/std.",
    )
    args = ap.parse_args()
    mnist_norm = not args.no_mnist_normalize

    img_dir = args.img_dir.resolve()
    if not img_dir.is_dir():
        raise FileNotFoundError(f"Image folder not found: {img_dir}")

    paths = sorted(
        p for p in img_dir.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    )
    if not paths:
        raise FileNotFoundError(f"No images ({', '.join(sorted(IMAGE_EXTENSIONS))}) in {img_dir}")

    tensors: list[tuple[str, np.ndarray]] = []
    h = w = 28
    for p in paths:
        sym = "input_" + _c_symbol_from_stem(p.stem)
        arr = load_and_preprocess(p, pad_to_32=args.pad_to_32, mnist_normalize=mnist_norm)
        h, w = arr.shape
        tensors.append((sym, arr))

    out_dir = args.out_dir.resolve()

    fp32_entries: list[tuple[str, np.ndarray, str, float | None]] = [
        (name, a.astype(np.float32), "float", None) for name, a in tensors
    ]
    emit_input_header(
        out_dir / "testimg_inputs_fp32.h",
        "fp32",
        "TESTIMG_INPUTS_FP32_H",
        fp32_entries,
        h=h,
        w=w,
    )
    print(f"Wrote {out_dir / 'testimg_inputs_fp32.h'}")

    for kind, (ctype, macro) in QUANT_KINDS.items():
        bits = int(kind.replace("int", ""))
        entries: list[tuple[str, np.ndarray, str, float | None]] = []
        for name, a in tensors:
            q, scale = symmetric_quantize(a.astype(np.float32), bits)
            entries.append((name, q, ctype, scale))
        emit_input_header(
            out_dir / f"testimg_inputs_{kind}.h",
            kind,
            f"TESTIMG_INPUTS_{macro}_H",
            entries,
            h=h,
            w=w,
        )
        print(f"Wrote {out_dir / f'testimg_inputs_{kind}.h'}")

    print(f"Processed {len(paths)} image(s), size {h}x{w}. Done.")


if __name__ == "__main__":
    main()
